on: [push]

name: Deploy Web App

on: push

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - name: 'Checkout Github Action' 
      uses: actions/checkout@master
    
    - name: Setup Node 10.x
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: 'npm install, build, and test'
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present
       
    - name: 'Update app'
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: |
            az storage blob delete-batch -s "build"  --connection-string ${{secrets.AZURE_CONNECTION_STRING}}
            az storage blob upload-batch -s "build" -d '$web'  --connection-string ${{secrets.AZURE_CONNECTION_STRING}}
